"""Fail-closed chronological portfolio orchestration for frozen V6.

This module connects verified signal selections, dated corporate-action events,
raw execution opens, and the existing rebalance engine. It is not a CLI and
does not authorize a performance run: the external Phase 1A/P6 completeness
and final-freeze gates must pass before production use.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import date, timedelta
from math import isclose, isfinite
from typing import Mapping, Sequence

from .accounting import (
    DebentureCoupon,
    DebentureEntitlement,
    DebentureRedemption,
    Dividend,
    DividendEntitlement,
    DividendPayment,
    LedgerEvent,
    PortfolioState,
    RightsEntitlement,
    SecurityConversion,
    ShareRatioAction,
    Trade,
)
from .costs import DeliveryCostModel
from .simulation import plan_and_execute_at_open


class HistoricalRunBlocked(RuntimeError):
    """Raised when required historical evidence or an accounting invariant is missing."""


@dataclass(frozen=True)
class SessionPrices:
    """Raw prices for one actual trading session, keyed by stable project symbol."""
    opens: Mapping[str, float]
    closes: Mapping[str, float]

    def __post_init__(self) -> None:
        for label, prices in (("open", self.opens), ("close", self.closes)):
            for symbol, price in prices.items():
                if not symbol or not isfinite(float(price)) or float(price) <= 0:
                    raise ValueError(f"invalid {label} price for {symbol!r}: {price!r}")


@dataclass(frozen=True)
class RebalanceInstruction:
    decision_date: date
    execution_date: date
    ranked_symbols: tuple[tuple[str, int], ...]
    selection_status: str = "PASS"

    def __post_init__(self) -> None:
        if self.execution_date <= self.decision_date:
            raise ValueError("execution_date must follow decision_date")
        if self.selection_status not in {"PASS", "PASS_FEWER_THAN_TARGET_HOLDINGS"}:
            raise ValueError(f"selection is not executable: {self.selection_status}")
        symbols = [symbol for symbol, _ in self.ranked_symbols]
        ranks = [rank for _, rank in self.ranked_symbols]
        if not symbols or any(not symbol for symbol in symbols):
            raise ValueError("ranked_symbols cannot be empty")
        if len(symbols) != len(set(symbols)):
            raise ValueError("ranked_symbols contains duplicate symbols")
        if ranks != list(range(1, len(ranks) + 1)):
            raise ValueError("ranks must be contiguous and ordered from 1")


@dataclass(frozen=True)
class HistoricalEvent:
    """One sourced event from the canonical event register."""
    event_id: str
    source_ref: str
    event: LedgerEvent
    verified: bool

    def __post_init__(self) -> None:
        if not self.event_id.strip() or not self.source_ref.strip():
            raise ValueError("historical events require event_id and source_ref")
        if not self.verified:
            raise HistoricalRunBlocked(f"unverified historical event: {self.event_id}")
        supported = (SecurityConversion, ShareRatioAction, DividendEntitlement, DividendPayment,
                     DebentureEntitlement, DebentureCoupon, DebentureRedemption)
        if not isinstance(self.event, supported):
            raise ValueError(
                "strategy trades are generated by the runner; rights use RightsLifecycle; "
                "legacy Dividend credits cash too early for historical use"
            )
        event_id = getattr(self.event, "event_id", None)
        if event_id is not None and event_id != self.event_id:
            raise ValueError(f"event_id mismatch for {self.event_id}")
        source_ref = getattr(self.event, "source_ref", None)
        if source_ref is not None and source_ref != self.source_ref:
            raise ValueError(f"source_ref mismatch for {self.event_id}")
        try:
            date.fromisoformat(self.event.date)
        except (TypeError, ValueError) as exc:
            raise ValueError(f"invalid event date for {self.event_id}") from exc


@dataclass(frozen=True)
class RightsLifecycle:
    """Verified rights entitlement and mandatory first-tradable-open renunciation."""
    event_id: str
    entitlement: RightsEntitlement
    first_tradable_date: date
    expected_first_tradable_open: float
    source_ref: str
    verified: bool

    def __post_init__(self) -> None:
        if not self.event_id.strip() or not self.source_ref.strip():
            raise ValueError("rights lifecycle requires event_id and source_ref")
        if not self.verified:
            raise HistoricalRunBlocked(f"unverified rights lifecycle: {self.event_id}")
        entitlement_date = date.fromisoformat(self.entitlement.date)
        if self.first_tradable_date <= entitlement_date:
            raise ValueError("rights first tradable date must follow entitlement date")
        if not isfinite(float(self.expected_first_tradable_open)) or self.expected_first_tradable_open <= 0:
            raise ValueError("expected rights raw open must be finite and positive")


@dataclass(frozen=True)
class RebalanceObservation:
    decision_date: date
    execution_date: date
    pretrade_nav: float
    posttrade_nav: float
    cash_after: float
    dividend_receivable_after: float
    positions_after: Mapping[str, int]
    transaction_costs: float
    return_from_previous_observation: float


@dataclass(frozen=True)
class HistoricalResult:
    initial_cash: float
    final_date: date
    final_nav: float
    final_state: PortfolioState
    rebalances: tuple[RebalanceObservation, ...]
    trades: tuple[Trade, ...]
    events_applied: tuple[str, ...]
    final_period_return: float


_EVENT_PRIORITY = {
    SecurityConversion: 0,
    ShareRatioAction: 0,
    DividendEntitlement: 1,
    DebentureEntitlement: 1,
    DebentureCoupon: 1,
    DebentureRedemption: 1,
    DividendPayment: 2,
}


def _apply_verified_event(state: PortfolioState, wrapped: HistoricalEvent) -> None:
    event = wrapped.event
    if wrapped.event_id in state.applied_event_ids:
        raise HistoricalRunBlocked(f"duplicate historical event: {wrapped.event_id}")
    if isinstance(event, SecurityConversion):
        state.apply_security_conversion(event)
    elif isinstance(event, ShareRatioAction):
        state.apply_share_ratio(event)
    elif isinstance(event, DividendEntitlement):
        state.apply_dividend_entitlement(event)
    elif isinstance(event, DividendPayment):
        state.apply_dividend_payment(event)
    elif isinstance(event, DebentureEntitlement):
        state.apply_debenture_entitlement(event)
    elif isinstance(event, DebentureCoupon):
        state.apply_debenture_coupon(event)
    elif isinstance(event, DebentureRedemption):
        state.apply_debenture_redemption(event)
    else:
        raise HistoricalRunBlocked(f"unsupported historical event type: {type(event).__name__}")
    # The debenture/dividend primitives already register their own event IDs.
    state.applied_event_ids.add(wrapped.event_id)


def run_historical_simulation(
    *,
    trading_dates: Sequence[date],
    session_prices: Mapping[date, SessionPrices],
    rebalances: Sequence[RebalanceInstruction],
    events: Sequence[HistoricalEvent],
    rights_lifecycles: Sequence[RightsLifecycle],
    cost_model: DeliveryCostModel,
    initial_cash: float = 25_000.0,
    target_weight: float = 0.20,
    holdings: int = 5,
) -> HistoricalResult:
    """Run the portfolio chronologically without changing signal or V6 rules.

    The caller must provide a complete, independently audited event register and
    marks. Missing raw opens, closes, source evidence, rights opens, or cashflow
    links fail closed. Returns are measured from one post-rebalance NAV to the
    next post-rebalance NAV, plus the final close-to-closeout interval.
    """
    supplied_sessions = list(trading_dates)
    if not supplied_sessions:
        raise ValueError("trading_dates cannot be empty")
    if len(set(supplied_sessions)) != len(supplied_sessions):
        raise ValueError("trading_dates contains duplicates")
    sessions = sorted(supplied_sessions)
    if any(b <= a for a, b in zip(sessions, sessions[1:])):
        raise ValueError("trading_dates must be strictly increasing")
    missing_sessions = [d for d in sessions if d not in session_prices]
    if missing_sessions:
        raise HistoricalRunBlocked(f"missing session prices: {missing_sessions[:5]}")
    if not isfinite(float(initial_cash)) or initial_cash <= 0:
        raise ValueError("initial_cash must be finite and positive")
    if holdings <= 0 or not isclose(target_weight * holdings, 1.0, abs_tol=1e-9):
        raise ValueError("target_weight must sum to 100% across holdings")

    session_set = set(sessions)
    first_date, final_date = sessions[0], sessions[-1]
    if len({x.event_id for x in events}) != len(events):
        raise ValueError("duplicate historical event IDs")
    if len({x.event_id for x in rights_lifecycles}) != len(rights_lifecycles):
        raise ValueError("duplicate rights lifecycle IDs")
    all_ids = [x.event_id for x in events] + [x.event_id for x in rights_lifecycles]
    if len(set(all_ids)) != len(all_ids):
        raise ValueError("event IDs must be unique across event and rights registers")

    event_dates: dict[date, list[HistoricalEvent]] = {}
    dividend_entitlements: dict[str, DividendEntitlement] = {}
    dividend_payments: dict[str, DividendPayment] = {}
    for wrapped in events:
        event_date = date.fromisoformat(wrapped.event.date)
        if not first_date <= event_date <= final_date:
            raise HistoricalRunBlocked(f"event outside simulation period: {wrapped.event_id}")
        if isinstance(wrapped.event, (SecurityConversion, ShareRatioAction, DividendEntitlement,
                                       DebentureEntitlement, DebentureCoupon, DebentureRedemption)):
            if event_date not in session_set:
                raise HistoricalRunBlocked(
                    f"market-effective event is not on a trading session: {wrapped.event_id} {event_date}"
                )
        event_dates.setdefault(event_date, []).append(wrapped)
        if isinstance(wrapped.event, DividendEntitlement):
            dividend_entitlements[wrapped.event_id] = wrapped.event
        elif isinstance(wrapped.event, DividendPayment):
            if wrapped.event.entitlement_event_id in dividend_payments:
                raise ValueError(f"duplicate payment for entitlement {wrapped.event.entitlement_event_id}")
            dividend_payments[wrapped.event.entitlement_event_id] = wrapped.event

    for entitlement_id, payment in dividend_payments.items():
        entitlement = dividend_entitlements.get(entitlement_id)
        if entitlement is None:
            raise HistoricalRunBlocked(f"payment references missing dividend entitlement: {entitlement_id}")
        if payment.date != entitlement.payment_date:
            raise HistoricalRunBlocked(
                f"dividend payment date mismatch for {entitlement_id}: "
                f"expected {entitlement.payment_date}, got {payment.date}"
            )

    rights_by_entitlement: dict[date, list[RightsLifecycle]] = {}
    rights_by_sale: dict[date, list[RightsLifecycle]] = {}
    for lifecycle in rights_lifecycles:
        entitlement_date = date.fromisoformat(lifecycle.entitlement.date)
        if entitlement_date not in session_set:
            raise HistoricalRunBlocked(
                f"rights entitlement date is not a trading session: {lifecycle.event_id}"
            )
        if lifecycle.first_tradable_date not in session_set:
            raise HistoricalRunBlocked(
                f"rights first-tradable date missing from trading calendar: {lifecycle.event_id}"
            )
        if not first_date <= entitlement_date < lifecycle.first_tradable_date <= final_date:
            raise HistoricalRunBlocked(f"rights lifecycle outside simulation period: {lifecycle.event_id}")
        rights_by_entitlement.setdefault(entitlement_date, []).append(lifecycle)
        rights_by_sale.setdefault(lifecycle.first_tradable_date, []).append(lifecycle)

    rebalance_by_date: dict[date, RebalanceInstruction] = {}
    decision_dates = set()
    for instruction in rebalances:
        if instruction.decision_date in decision_dates:
            raise ValueError(f"duplicate rebalance decision date: {instruction.decision_date}")
        decision_dates.add(instruction.decision_date)
        if instruction.execution_date in rebalance_by_date:
            raise ValueError(f"multiple rebalances on {instruction.execution_date}")
        if instruction.decision_date not in session_set or instruction.execution_date not in session_set:
            raise HistoricalRunBlocked("rebalance dates must be actual trading sessions")
        if instruction.decision_date.month not in (3, 6, 9, 12):
            raise HistoricalRunBlocked(f"non-quarterly decision date: {instruction.decision_date}")
        same_month_sessions = [
            session for session in sessions
            if session.year == instruction.decision_date.year
            and session.month == instruction.decision_date.month
        ]
        if not same_month_sessions or max(same_month_sessions) != instruction.decision_date:
            raise HistoricalRunBlocked(
                f"decision date is not the final actual session of its quarter month: {instruction.decision_date}"
            )
        decision_index = sessions.index(instruction.decision_date)
        if decision_index + 1 >= len(sessions) or sessions[decision_index + 1] != instruction.execution_date:
            raise HistoricalRunBlocked(
                f"execution must be the next actual trading session after {instruction.decision_date}"
            )
        if len(instruction.ranked_symbols) > holdings:
            raise ValueError("selected symbols exceed frozen holdings count")
        rebalance_by_date[instruction.execution_date] = instruction
    if not rebalance_by_date:
        raise ValueError("at least one rebalance instruction is required")

    # Every entitlement with a payment date inside the run must have one sourced payment event.
    for entitlement_id, entitlement in dividend_entitlements.items():
        if entitlement.payment_date <= final_date.isoformat() and entitlement_id not in dividend_payments:
            raise HistoricalRunBlocked(f"missing dividend payment event for {entitlement_id}")

    state = PortfolioState(cash=float(initial_cash))
    applied: list[str] = []
    rights_quantities: dict[str, int] = {}
    executed_trades: list[Trade] = []
    observations: list[RebalanceObservation] = []
    previous_nav = float(initial_cash)
    last_posttrade_nav: float | None = None

    current = first_date
    while current <= final_date:
        todays_events = event_dates.get(current, [])
        todays_actions = [
            (_EVENT_PRIORITY[type(wrapped.event)], index, "event", wrapped)
            for index, wrapped in enumerate(todays_events)
        ]
        next_order = len(todays_actions)
        todays_actions.extend(
            (0, next_order + index, "rights_entitlement", lifecycle)
            for index, lifecycle in enumerate(
                sorted(rights_by_entitlement.get(current, []), key=lambda x: x.event_id)
            )
        )
        for _, _, action_kind, payload in sorted(todays_actions, key=lambda row: (row[0], row[1])):
            if action_kind == "event":
                wrapped = payload
                _apply_verified_event(state, wrapped)
                applied.append(wrapped.event_id)
            else:
                lifecycle = payload
                if lifecycle.event_id in state.applied_event_ids:
                    raise HistoricalRunBlocked(f"duplicate rights entitlement: {lifecycle.event_id}")
                quantity = state.apply_rights_entitlement(lifecycle.entitlement)
                state.applied_event_ids.add(lifecycle.event_id)
                rights_quantities[lifecycle.event_id] = quantity
                applied.append(lifecycle.event_id)

        if current in session_set:
            prices = session_prices[current]
            for lifecycle in sorted(rights_by_sale.get(current, []), key=lambda x: x.event_id):
                quantity = rights_quantities.get(lifecycle.event_id)
                if quantity is None:
                    raise HistoricalRunBlocked(f"rights sale has no prior entitlement: {lifecycle.event_id}")
                symbol = lifecycle.entitlement.re_symbol
                raw_open = prices.opens.get(symbol)
                if raw_open is None:
                    raise HistoricalRunBlocked(f"missing raw rights open for {symbol} on {current}")
                if not isclose(float(raw_open), lifecycle.expected_first_tradable_open, rel_tol=0, abs_tol=1e-8):
                    raise HistoricalRunBlocked(
                        f"rights raw open mismatch for {symbol} on {current}: "
                        f"price_store={raw_open}, verified_source={lifecycle.expected_first_tradable_open}"
                    )
                held_rights = state.shares(symbol)
                if held_rights != quantity:
                    raise HistoricalRunBlocked(
                        f"rights position mismatch for {lifecycle.event_id}: "
                        f"expected {quantity}, ledger holds {held_rights}"
                    )
                if quantity:
                    gross = quantity * float(raw_open)
                    costs = cost_model.costs(current, "SELL", gross, scrips_sold=1, slippage=0.001)
                    trade = Trade(current.isoformat(), symbol, "SELL", quantity, float(raw_open), costs)
                    state.apply_trade(trade)
                    executed_trades.append(trade)
                applied.append(f"{lifecycle.event_id}:RENOUNCE")

            instruction = rebalance_by_date.get(current)
            if instruction is not None:
                step = plan_and_execute_at_open(
                    state=state,
                    decision_date=instruction.decision_date,
                    execution_date=instruction.execution_date,
                    ranked_symbols=instruction.ranked_symbols,
                    execution_opens=prices.opens,
                    cost_model=cost_model,
                    target_weight=target_weight,
                    holdings=holdings,
                )
                if step.execution is None:
                    raise HistoricalRunBlocked(
                        f"rebalance blocked on {current}: {step.plan.block_reason}"
                    )
                state = step.execution.state
                executed_trades.extend(step.execution.trades)
                posttrade_nav = step.execution.ending_nav
                interval_return = posttrade_nav / previous_nav - 1.0
                observations.append(RebalanceObservation(
                    decision_date=instruction.decision_date,
                    execution_date=current,
                    pretrade_nav=step.pretrade_nav,
                    posttrade_nav=posttrade_nav,
                    cash_after=state.cash,
                    dividend_receivable_after=state.dividend_receivable,
                    positions_after=dict(state.positions),
                    transaction_costs=step.execution.total_costs,
                    return_from_previous_observation=interval_return,
                ))
                previous_nav = posttrade_nav
                last_posttrade_nav = posttrade_nav

        current += timedelta(days=1)

    final_prices = session_prices[final_date].closes
    try:
        final_nav = state.market_value(final_prices)
    except ValueError as exc:
        raise HistoricalRunBlocked(f"final close NAV cannot be marked: {exc}") from exc
    base_nav = last_posttrade_nav if last_posttrade_nav is not None else initial_cash
    final_period_return = final_nav / base_nav - 1.0
    return HistoricalResult(
        initial_cash=float(initial_cash),
        final_date=final_date,
        final_nav=final_nav,
        final_state=state,
        rebalances=tuple(observations),
        trades=tuple(executed_trades),
        events_applied=tuple(applied),
        final_period_return=final_period_return,
    )
